// Code generated by logcopter-gen; DO NOT EDIT.

package output

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.vault-envrc-generator.pkg.output")
