// Code generated by logcopter-gen; DO NOT EDIT.

package seed

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.vault-envrc-generator.pkg.seed")
